ePatient/Controllers/ProblemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ePatient.DAL;
using ePatient.Models;

namespace ePatient.Controllers
{
    public class ProblemsController : BaseController
    {
        private ePatientDB db = new ePatientDB();

        // GET: Problems
        public async Task<ActionResult> Index()
        {
            var problems = db.Problems.Include(p => p.Patient);
            return View(await problems.ToListAsync());
        }

        // GET: Problems/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Problem problem = await db.Problems.FindAsync(id);
            if (problem == null)
            {
                return HttpNotFound();
            }
            return View(problem);
        }

        // GET: Problems/Create/patientid
        public ActionResult Create(int? id)
        {
            //ViewBag.PatientID = new SelectList(db.Patients, "PatientID", "Title");
            if (id != null)
            {
                //ViewBag.PatientID = patientid;
                Patient patient = db.Patients.Find(id);
                Problem _problem = new Problem();
                _problem.PatientID = id.Value;
                _problem.Patient = patient;

                IEnumerable<Organ> organTypes = Enum.GetValues(typeof(Organ))
                                                       .Cast<Organ>();
                _problem.OrganList = from organ in organTypes
                                    select new SelectListItem
                                    {
                                        Text = organ.ToString(),
                                        Value = ((int)organ).ToString()
                                    };

               return View(_problem);
            }
            else
            {
                return HttpNotFound();
            }
            
        }

        // POST: Problems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ProblemID,PatientID,Organs,Details,ReportedOn")] Problem problem)
        {
            if (ModelState.IsValid)
            {
                db.Problems.Add(problem);
                await db.SaveChangesAsync();
                return RedirectToAction("Edit", "ePatient", new { id = problem.PatientID });
            }
            Patient patient = db.Patients.Find(problem.PatientID);
            problem.Patient = patient;

            //ViewBag.PatientID = new SelectList(db.Patients, "PatientID", "Title", problem.PatientID);
            return View(problem);
        }

        // GET: Problems/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Problem problem = await db.Problems.FindAsync(id);
            if (problem == null)
            {
                return HttpNotFound();
            }
           // ViewBag.PatientID = new SelectList(db.Patients, "PatientID", "Title", problem.PatientID);
            IEnumerable<Organ> organTypes = Enum.GetValues(typeof(Organ))
                                                     .Cast<Organ>();
            problem.OrganList = from organ in organTypes
                                select new SelectListItem
                                {
                                    Text = organ.ToString(),
                                    Value = ((int)organ).ToString()
                                };
            

            ViewBag.PatientID = problem.PatientID;
            Patient patient = db.Patients.Find(problem.PatientID);
            problem.PatientID = problem.PatientID;
            problem.Patient = patient;

           

            return View(problem);
        }

        // POST: Problems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ProblemID,PatientID,Organs,Details,ReportedOn")] Problem problem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(problem).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Edit", "ePatient", new { id=problem.PatientID});
            }
            ViewBag.PatientID = new SelectList(db.Patients, "PatientID", "Title", problem.PatientID);

            return View(problem);
        }

        // GET: Problems/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Problem problem = await db.Problems.FindAsync(id);
            if (problem == null)
            {
                return HttpNotFound();
            }

            Patient patient = db.Patients.Find(problem.PatientID);
            problem.PatientID = problem.PatientID;
            problem.Patient = patient;

            return View(problem);
        }

        // POST: Problems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Problem problem = await db.Problems.FindAsync(id);
            db.Problems.Remove(problem);
            await db.SaveChangesAsync();
            return RedirectToAction("Edit", "ePatient", new { id = problem.PatientID });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ePatient/Controllers/ePatientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ePatient.Models;
using ePatient.DAL;
using ePatient.Services;
using System.Threading;
using System.Web.Helpers;
using System.Web.Script.Serialization;

namespace ePatient.Controllers
{
    public class ePatientController : BaseController
    {
        private ePatientDB db = new ePatientDB();

        // GET: /ePatient/
        public ActionResult Index()
        {
            if (Convert.ToString(Session["ISLOGGEDIN"]) != "True")
            {
                return RedirectToAction("LogOn", "UserAccount", null);
            }
               
            else
                return View(db.Patients.ToList());
        }

                // GET: /ePatient/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PatientInputModel patientinfo = ManagePatient.Instance.getSinglePatientDetails(id.Value);
            if (patientinfo == null)
            {
                return HttpNotFound();
            }
            return View(patientinfo);
        }

        // GET: /ePatient/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /ePatient/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include="PatientID,Title,Fname,Lname,DOB,Sex,EnrollmentDate,CSN,issueDate")] Patient patient)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        SmartCard _smart = new SmartCard();
        //        _smart.PersonID = patient.PatientID;
        //        _smart.issueDate = patient.SmartCard.issueDate;
        //        _smart.CSN = patient.SmartCard.CSN;

        //        ManagePatient.Instance.CreatePatient(patient,_smart);
        //        //db.Patients.Add(patient);
        //        //db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(patient);
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PatientInputModel patient)
        {
            if (ModelState.IsValid)
            {
                 ManagePatient.Instance.CreatePatient(patient);
                //db.Patients.Add(patient);
                //db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(patient);
        }

        // GET: /ePatient/Edit/5
        public ActionResult Edit(int? id)
        {
           // if (id == null)
           // {
           //     return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
           // }
            
           // PatientInputModel patientinfo = ManagePatient.Instance.getPatientInfoForEdit(id.Value);
           // if (patientinfo == null)
           // {
           //     return HttpNotFound();
           // }
           //return View(patientinfo);
            return View();
        }

        public ActionResult GetPatientInfo(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Patient patient = db.Patients.Find(id);

            PatientInputModel patientinfo = ManagePatient.Instance.getPatientInfoForEdit(id.Value);
            // JavaScriptSerializer serializer = new JavaScriptSerializer();
            // ViewBag.InitialData = serializer.Serialize(patientinfo); 
            if (patientinfo == null)
            {
                return HttpNotFound();
            }
            //return View(patientinfo);
            return Json(patientinfo, JsonRequestBehavior.AllowGet);
        }

        // POST: /ePatient/Edit/5
       [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit(PatientInputModel patient)
        {
            if (ModelState.IsValid)
            {
                //SmartCard card = new SmartCard();
                //card.PersonID = patient.PatientID;
                //card.CSN = patient.CSN;
                //card.issueDate = patient.issueDate;
                //ManagePatient.Instance.EditSmartCard(card);

                ManagePatient.Instance.EditPatient(patient);

                //db.Entry(patient).State = EntityState.Modified;
                //db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(patient);
        }

        // GET: /ePatient/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: /ePatient/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Patient patient = db.Patients.Find(id);
            db.Patients.Remove(patient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Search()
        {
            return View();
        }

        #region Code for Jquery Search Grid
        //public JsonResult PatientSearch(string Fname,string Lname,string phone,string csn)
        //{
        //    //PatientSearchModel _patients = new PatientSearchModel();
        //    Fname = "Alex";
        //    double dbCsn;
        //    if (csn != "")
        //        dbCsn = Convert.ToDouble(csn);
        //    else
        //        dbCsn = Convert.ToDouble(0);

        //   List<PatientSearchList> list = ManagePatient.Instance.SearchPatient(Fname, Lname, phone, dbCsn);

        //    return Json(list, JsonRequestBehavior.AllowGet);
        //}
        #endregion

        #region Search code for KO search
        public JsonResult PatientSearch(string Fname, string Lname, string phone, string csn)
        {
            Fname = "Al";
            double dbCsn;
            if (csn != "")
                dbCsn = Convert.ToDouble(csn);
            else
                dbCsn = Convert.ToDouble(0);

            var searchedlist = ManagePatient.Instance.SearchPatient(Fname, Lname, phone, dbCsn); 

            return Json(new { Items = searchedlist });
        }
        public JsonResult PatientList()
        {
            string Fname = "";
            string Lname = "";
            string phone = "";
            string csn = "";

            Fname = "Al";
            double dbCsn;
            if (csn != "")
                dbCsn = Convert.ToDouble(csn);
            else
                dbCsn = Convert.ToDouble(0);

            var searchedlist = ManagePatient.Instance.SearchPatient(Fname, Lname, phone, dbCsn);

            return Json(new { Items = searchedlist });
        }
        #endregion


        [HttpPost]
        public JsonResult ProcessForm(PatientInputModel patient)
        {
            
            Thread.Sleep(2000);
            if(patient.PatientID==0) //Add New Patient
            {
                if (ManagePatient.Instance.CreatePatient(patient))
                    return Json(new { success = "1", context = "Add" });
                else
                    return Json(new { success = "0", context = "Add" }); 
            }
            else //Edit Patient
            {
                if (ManagePatient.Instance.EditPatient(patient))
                    return Json(new { success = "1", context = "Edit" });
                else
                    return Json(new { success = "0", context = "Edit" }); 
            }
        }

        
        //[HttpPost]
        //public string ProcessForm2(string test)
        //{
        //    return "<h2>Hi!</h2>" + test;
        //}
    }
}

ePatient/Views/ePatient/Details.cshtml
@model ePatient.Models.PatientInputModel

@{
    ViewBag.Title = "Patient Details";
}

<h2></h2>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PatientID }) |
    @Html.ActionLink("Back to List", "Index")
</p>   
<div>

    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">Patient Details</h3>
        </div>
        <div class="panel-body">
            <dt>
                @Html.DisplayNameFor(model => model.Title)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Title)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Fname)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Fname)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Lname)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Lname)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.DOB)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.DOB)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Sex)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Sex)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.EnrollmentDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.EnrollmentDate)
            </dd>

            </div>
        </div>
    </div>



<div class="panel-group" id="accordion">
    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-2">
                    <h2 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                            Allergies
                        </a>
                    </h2>
                </div>
                <div class=" col-md-2 col-md-offset-8">
                    @*<h2 class="panel-title">@Html.ActionLink("Add New", "Create", "Allergies", new { id = Model.PatientID }, null)</h2>*@
                    <button class="btn btn-default" type="button" data-toggle="modal" data-target="#myModal">Launch modal</button>
                    <a data-toggle="modal" href="/Allergies/Create" data-target="#myModal">Click me</a>
                </div>
            </div>
        </div>
        <div id="collapseOne" class="panel-collapse collapse in"> @* 'collapse in' --> details remain open*@
            
            <table class="table table-condensed table-striped table-hover">
                <tr>
                    <th>
                        Details
                    </th>
                    <th>
                        Detected On
                    </th>
                    <th>
                        Reported On
                    </th>
                    <th></th>
                </tr>

                @foreach (var allergyitem in Model.Allergies)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => allergyitem.Details)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => allergyitem.DetectedOn)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => allergyitem.ReportedOn)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", "Allergies", new { id = allergyitem.AllergyID }, null) |
                            @Html.ActionLink("Delete", "Delete", "Allergies", new { id = allergyitem.AllergyID }, null)
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>


    <div class="panel panel-primary">
        <div class="panel-heading">
            <div class="row">
                <div class="col-md-2">
                    <h2 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                            Problems
                        </a>
                    </h2>
                </div>
                <div class="col-md-offset-11">
                    <h2 class="panel-title">@Html.ActionLink("Add New", "Create", "Problems", new { id = Model.PatientID }, null)</h2>
                </div>
            </div>

        </div>
        <div id="collapseTwo" class="panel-collapse collapse">
            <div class="panel-body">
                <table class="table table-condensed table-striped table-hover">
                    <tr>
                        <th>
                            Organ
                        </th>
                        <th>
                            Details
                        </th>
                        <th>
                            Reported On
                        </th>
                        @*<th></th>*@
                    </tr>

                    @foreach (var problemitem in Model.Problems)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => problemitem.Organs)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => problemitem.Details)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => problemitem.ReportedOn)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Problems", new { id = problemitem.ProblemID }, null) |
                        @Html.ActionLink("Delete", "Delete", "Problems", new
                   {
                       @class = "openDialog",
                       data_dialog_id = "aboutDialog",
                       data_dialog_title = "About Us",
                       id = problemitem.ProblemID
                   }, null)
                    </td>
                </tr>
            }

                </table>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="myModalLabel">Patient Allergies</h4>
            </div>
            <div class="modal-body">
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

ePatient/Views/ePatient/Edit - Ajax.cshtml
@model ePatient.Models.PatientInputModel
@{
    ViewBag.Title = "Edit";
}

<script src="@Url.Content("~/Scripts/Patient/Patient.js")" type="text/javascript"></script>
<script src="~/Scripts/knockout-2.0.0.js"></script>
<script src="~/Scripts/knockout.mapping-latest.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#divProgress").css("display","none");
    });
</script>


    <ol class="breadcrumb">
        <li><a href="/ePatient/Index">Patients</a></li>
        <li class="active">Modify</li>
    </ol>

    <div class="row">
        <div class="col-md-3">
            <h2>Edit Patient</h2>
        </div>
        <div class="col-md-9 pull-right" style="margin-top:20px">
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>


    @using (Html.BeginForm("","",FormMethod.Post,new {id="patientForm", @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal well">

            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.PatientID, new { id = "hdnPatientId" })
            @Html.Hidden("hdnResult")

            <div class="form-group">
                @*<div class="col-md-1"></div>*@
                <div class="col-md-11">
                    @Html
                    @Html.EditorFor(model => model.Title, new { @class = "form-control" })
                </div>
            </div>

        <div class="form-group">
            @*<div class="col-md-1"></div>*@
            @*@Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2", style = "padding-top:10px" })*@
            <div class="col-md-11">
                @Html.EditorFor(model => model.Fname, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @*<div class="col-md-1"></div>*@
            <div class="col-md-11">
                @Html.EditorFor(model => model.Lname, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-2"></div>
            @*@Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2", style = "padding-top:10px" })*@
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.Sex, "Male") Male
                @Html.RadioButtonFor(model => model.Sex, "Female") Female
                @Html.ValidationMessageFor(model => model.Sex)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-1"></div>
            <div class="col-md-11">
                @Html.EditorFor(model => model.DOB, new { @class = "datepicker" })
                @Html.ValidationMessageFor(model => model.DOB)
            </div>
        </div>

        <div class="form-group">
            @*<div class="col-md-2"></div>*@
            @*@Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2", style = "padding-top:10px" })*@
            <div class="col-md-11">
                @Html.EditorFor(model => model.Address, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @*<div class="col-md-1"></div>*@
            <div class="col-md-11">
                @Html.EditorFor(model => model.City, new { @class = "form-control" })
            </div>
        </div>
        
        <div class="form-group">
            @*<div class="col-md-1"></div>*@
            <div class="col-md-11">
                @Html.EditorFor(model => model.Pincode, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @*<div class="col-md-1"></div>*@
            @*@Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2", style = "padding-top:10px" })*@
            <div class="col-md-11">
                @Html.EditorFor(model => model.Phone, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @*<div class="col-md-1"></div>*@
            <div class="col-md-11">
                @Html.EditorFor(model => model.Email, new { @class = "form-control" })
            </div>
        </div>
        
        <div class="form-group">
            @*<div class="col-md-1"></div>*@
            <div class="col-md-11">
                @Html.EditorFor(model => model.EnrollmentDate, new { @class = "datepicker" })
            </div>
        </div>  

        <div class="form-group">
            @*<div class="col-md-1"></div>*@
            <div class="col-md-11">
                @Html.EditorFor(model => model.CSN, new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @*<div class="col-md-1"></div>*@
            <div class="col-md-11">
                @Html.EditorFor(model => model.issueDate, new { @class = "datepicker" })
            </div>
        </div> 

<div class="form-group">

    <div class="col-md-offset-11" style="padding-top:10px">
        <input type="button" value="Save" class="btn btn-primary" onclick="SavePatient();" />
    </div>
</div>
<div class="form-group">
    <div class="col-md-offset-10">
        <div id="divMsg">
            <div id="divProgress">
                <img src="~/Content/images/wait.gif" />
            </div>
        </div>
    </div>
</div>

</div>


}



<div class="panel panel-info">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-2">
                <h2 class="panel-title">Allergies</h2>
            </div>
            <div class="col-md-offset-11">
                <h2 class="panel-title">@Html.ActionLink("Add New", "Create", "Allergies", new { id = Model.PatientID }, null)</h2>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <table class="table table-condensed table-striped table-hover">
            <tr>
                <th>
                    Details
                </th>
                <th>
                    Detected On
                </th>
                <th>
                    Reported On
                </th>
                <th></th>
            </tr>

            @foreach (var allergyitem in Model.Allergies)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => allergyitem.Details)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => allergyitem.DetectedOn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => allergyitem.ReportedOn)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Allergies", new { id = allergyitem.AllergyID }, null) |
                        @Html.ActionLink("Delete", "Delete", "Allergies", new { id = allergyitem.AllergyID }, null)
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

<div class="panel panel-info">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-2">
                <h2 class="panel-title">Problems</h2>
            </div>
            <div class="col-md-offset-11">
                <h2 class="panel-title">@Html.ActionLink("Add New", "Create", "Problems", new { id = Model.PatientID }, null)</h2>
            </div>
        </div>

    </div>
    <div class="panel-body">
        <table class="table table-condensed table-striped table-hover">
            <tr>
                <th>
                    Organ
                </th>
                <th>
                    Details
                </th>
                <th>
                    Reported On
                </th>
                @*<th></th>*@
            </tr>

            @foreach (var problemitem in Model.Problems)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => problemitem.Organs)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => problemitem.Details)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => problemitem.ReportedOn)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", "Problems", new { id = problemitem.ProblemID }, null) |
                        @Html.ActionLink("Delete", "Delete", "Problems", new
                   {
                       @class = "openDialog",
                       data_dialog_id = "aboutDialog",
                       data_dialog_title = "About Us",
                       id = problemitem.ProblemID
                   }, null)
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

    @section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    }