ePatient/Controllers/ePatientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ePatient.Models;
using ePatient.DAL;
using ePatient.Services;
using System.Threading;
using System.Web.Helpers;
using System.Web.Script.Serialization;

namespace ePatient.Controllers
{
    public class ePatientController : BaseController
    {
        private ePatientDB db = new ePatientDB();

        // GET: /ePatient/
        public ActionResult Index()
        {
            if (Convert.ToString(Session["ISLOGGEDIN"]) != "True")
            {
                return RedirectToAction("LogOn", "UserAccount", null);
            }
               
            else
                return View(db.Patients.ToList());
        }

                // GET: /ePatient/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PatientInputModel patientinfo = ManagePatient.Instance.getSinglePatientDetails(id.Value);
            if (patientinfo == null)
            {
                return HttpNotFound();
            }
            return View(patientinfo);
        }

        // GET: /ePatient/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /ePatient/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include="PatientID,Title,Fname,Lname,DOB,Sex,EnrollmentDate,CSN,issueDate")] Patient patient)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        SmartCard _smart = new SmartCard();
        //        _smart.PersonID = patient.PatientID;
        //        _smart.issueDate = patient.SmartCard.issueDate;
        //        _smart.CSN = patient.SmartCard.CSN;

        //        ManagePatient.Instance.CreatePatient(patient,_smart);
        //        //db.Patients.Add(patient);
        //        //db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(patient);
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PatientInputModel patient)
        {
            if (ModelState.IsValid)
            {
                 ManagePatient.Instance.CreatePatient(patient);
                //db.Patients.Add(patient);
                //db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(patient);
        }

        // GET: /ePatient/Edit/5
        public ActionResult Edit(int? id)
        {
           // if (id == null)
           // {
           //     return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
           // }
            
           // PatientInputModel patientinfo = ManagePatient.Instance.getPatientInfoForEdit(id.Value);
           // if (patientinfo == null)
           // {
           //     return HttpNotFound();
           // }
           //return View(patientinfo);
            return View();
        }

        public ActionResult GetPatientInfo(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Patient patient = db.Patients.Find(id);

            PatientInputModel patientinfo = ManagePatient.Instance.getPatientInfoForEdit(id.Value);
            // JavaScriptSerializer serializer = new JavaScriptSerializer();
            // ViewBag.InitialData = serializer.Serialize(patientinfo); 
            if (patientinfo == null)
            {
                return HttpNotFound();
            }
            //return View(patientinfo);
            return Json(patientinfo, JsonRequestBehavior.AllowGet);
        }

        // POST: /ePatient/Edit/5
       [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit(PatientInputModel patient)
        {
            if (ModelState.IsValid)
            {
                //SmartCard card = new SmartCard();
                //card.PersonID = patient.PatientID;
                //card.CSN = patient.CSN;
                //card.issueDate = patient.issueDate;
                //ManagePatient.Instance.EditSmartCard(card);

                ManagePatient.Instance.EditPatient(patient);

                //db.Entry(patient).State = EntityState.Modified;
                //db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(patient);
        }

        // GET: /ePatient/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Patient patient = db.Patients.Find(id);
            if (patient == null)
            {
                return HttpNotFound();
            }
            return View(patient);
        }

        // POST: /ePatient/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Patient patient = db.Patients.Find(id);
            db.Patients.Remove(patient);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Search()
        {
            return View();
        }

        #region Code for Jquery Search Grid
        //public JsonResult PatientSearch(string Fname,string Lname,string phone,string csn)
        //{
        //    //PatientSearchModel _patients = new PatientSearchModel();
        //    Fname = "Alex";
        //    double dbCsn;
        //    if (csn != "")
        //        dbCsn = Convert.ToDouble(csn);
        //    else
        //        dbCsn = Convert.ToDouble(0);

        //   List<PatientSearchList> list = ManagePatient.Instance.SearchPatient(Fname, Lname, phone, dbCsn);

        //    return Json(list, JsonRequestBehavior.AllowGet);
        //}
        #endregion

        #region Search code for KO search
        public JsonResult PatientSearch(string Fname, string Lname, string phone, string csn)
        {
            Fname = "Al";
            double dbCsn;
            if (csn != "")
                dbCsn = Convert.ToDouble(csn);
            else
                dbCsn = Convert.ToDouble(0);

            var searchedlist = ManagePatient.Instance.SearchPatient(Fname, Lname, phone, dbCsn); 

            return Json(new { Items = searchedlist });
        }
        public JsonResult PatientList()
        {
            string Fname = "";
            string Lname = "";
            string phone = "";
            string csn = "";

            Fname = "Al";
            double dbCsn;
            if (csn != "")
                dbCsn = Convert.ToDouble(csn);
            else
                dbCsn = Convert.ToDouble(0);

            var searchedlist = ManagePatient.Instance.SearchPatient(Fname, Lname, phone, dbCsn);

            return Json(new { Items = searchedlist });
        }
        #endregion


        [HttpPost]
        public JsonResult ProcessForm(PatientInputModel patient)
        {
            
            Thread.Sleep(2000);
            if(patient.PatientID==0) //Add New Patient
            {
                if (ManagePatient.Instance.CreatePatient(patient))
                    return Json(new { success = "1", context = "Add" });
                else
                    return Json(new { success = "0", context = "Add" }); 
            }
            else //Edit Patient
            {
                if (ManagePatient.Instance.EditPatient(patient))
                    return Json(new { success = "1", context = "Edit" });
                else
                    return Json(new { success = "0", context = "Edit" }); 
            }
        }

        
        //[HttpPost]
        //public string ProcessForm2(string test)
        //{
        //    return "<h2>Hi!</h2>" + test;
        //}
    }
}

ePatient/Views/Shared/PatientInfoPartial.cshtml
@model ePatient.Models.PatientInputModel

<div class="form-horizontal well">

    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.PatientID, new { id = "hdnPatientId" })

    <div class="form-group">
        <div class="col-md-1"></div>
        @*@Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2", style = "padding-top:10px" })*@
        <div class="col-md-11">
            <div class="row">
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Title, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Title)
                </div>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Fname, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Fname)
                </div>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Lname, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Lname)
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-1"></div>
        <div class="col-md-11">
            <div class="row">
                <div class="col-md-4">
                    @Html.RadioButtonFor(model => model.Sex, "Male", true) Male
                    @Html.RadioButtonFor(model => model.Sex, "Female", false) Female
                    @Html.ValidationMessageFor(model => model.Sex)
                </div>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.DOB, new { @class = "datepicker" })
                    @Html.ValidationMessageFor(model => model.DOB)
                </div>

            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-1"></div>
        <div class="col-md-11">
            <div class="row">
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Address, new { @class = "form-control" })
                </div>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.City, new { @class = "form-control" })
                </div>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Pincode, new { @class = "form-control" })
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-1"></div>
        <div class="col-md-11">
            <div class="row">
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Phone, new { @class = "form-control" })
                </div>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.Email, new { @class = "form-control" })
                </div>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.EnrollmentDate, new { @class = "datepicker" })
                    @Html.ValidationMessageFor(model => model.EnrollmentDate)
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-1"></div>
        <div class="col-md-11">
            <div class="row">
                <div class="col-md-4">
                    @Html.EditorFor(model => model.CSN, new { @class = "form-control" })
                </div>
                <div class="col-md-4">
                    @Html.EditorFor(model => model.issueDate, new { @class = "datepicker" })
                    @Html.ValidationMessageFor(model => model.issueDate)
                </div>

            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-11 col-md-10" style="padding-top:10px">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </div>
</div>

ePatient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@("Patient Portal" + (!string.IsNullOrEmpty(ViewBag.Title) ? " - " + ViewBag.Title : ""))</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockout")
    @RenderSection("scripts", required: false)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink(@Resources.PortalHeading, "Index", "ePatient", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Patients", "Index", "ePatient")</li>
                    <li>@Html.ActionLink("Facilities", "Index", "Facilities")</li>
                    <li>@Html.ActionLink("Users", "Index", "Users")</li>
                    
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink(@Resources.Logout, "LogOff", "UserAccount", routeValues: null, htmlAttributes: new { id = "logoffLink" })</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
        @*<footer style="padding-top:60px">
            <hr />
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            
        </footer>*@
        <h2></h2>
        <br />
        <nav class="navbar navbar-inverse navbar-f-collapse">
            <div class="container">
                <div class="navbar-text">
                    <p> &copy; @DateTime.Now.Year - My ASP.NET Application</p>
                </div>
           </div>
        </nav>
    </div>

   
   
</body>
</html>

ePatient/Views/Shared/_LogOn.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@("Patient Portal - LogOn")</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/knockout")
    @RenderSection("scripts", required: false)

    @*----------------Region Required for Localization-----------------------*@
    @{
        var culture = System.Threading.Thread.CurrentThread.CurrentUICulture.Name.ToLowerInvariant();
    }

    @helper selected(string c, string culture)
    {
    if (c == culture)
    {
        @:checked="checked"
    }
    }

    @*------------------- Region ends--------------------------------------*@

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                @Html.ActionLink(@Resources.PortalHeading, "LogOn", "UserAccount", null, new { @class = "navbar-brand" })
                
            </div>
            @***------------------- Region for Culture set -------------------***@
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                        @using (Html.BeginForm("SetCulture", "UserAccount"))
                        {
                        <li>
                            <span class="navbar-text"><input name="culture" id="en-us" value="en-us" type="radio" @selected("en-us", culture) /> English</span> 
                            <span class="navbar-text"><input name="culture" id="pt" value="pt" type="radio" @selected("pt", culture) /> Portugese</span>

</li>
                        }
                </ul>
            </div>
            @***------------------- Culture set Region Ends ------------------***@
       </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
        @*<footer style="padding-top:60px">
            <hr />
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        (function ($) {
            $("input[type = 'radio']").click(function () {
                $(this).parents("form").submit(); // post form
            });

        })(jQuery);
    </script>
</body>
</html>